spring.application.name=DoTheFlop

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

application.jwt.secret=SuperSecretHackathonKey1234567890ValueThatIsLongEnoughForHS256
application.jwt.expiration=7d